[package]
name = "guessing-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
dialoguer = "0.11.0"
{ version = "0.7", features = ["fuzzy-select"] }
rand = "0.8.5"
